name: my_account_book
description: "Stable Premium Monthly Account Book"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  # 버전 충돌 및 네트워크 차단을 피하기 위해 안정 버전으로 고정
  excel: 2.1.0  
  path_provider: ^2.1.2
  share_plus: ^7.0.0

flutter:
  uses-material-design: true
