name: my_account_book
description: "Premium Monthly Account Book"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  # 충돌 방지를 위해 안정 버전으로 명시
  excel: 4.0.3
  path_provider: ^2.1.2
  share_plus: ^7.2.1

flutter:
  uses-material-design: true
