name: my_account_book
description: "Premium Monthly Account Book - Stable Version"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
